Name:           ros-kinetic-people
Version:        1.0.10
Release:        1%{?dist}
Summary:        ROS people package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/people
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-kinetic-face-detector
Requires:       ros-kinetic-leg-detector
Requires:       ros-kinetic-people-msgs
Requires:       ros-kinetic-people-tracking-filter
Requires:       ros-kinetic-people-velocity-tracker
BuildRequires:  ros-kinetic-catkin

%description
The people stack holds algorithms for perceiving people from a number of
sensors.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Tue Aug 09 2016 Dan Lazewatsky <dan@lazewatsky.com> - 1.0.10-1
- Autogenerated by Bloom

* Mon Jul 25 2016 Dan Lazewatsky <dan@lazewatsky.com> - 1.0.10-0
- Autogenerated by Bloom

