Name:           ros-jade-people-velocity-tracker
Version:        1.0.10
Release:        0%{?dist}
Summary:        ROS people_velocity_tracker package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/people_velocity_tracker
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-jade-easy-markers
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-kalman-filter
Requires:       ros-jade-leg-detector
Requires:       ros-jade-people-msgs
Requires:       ros-jade-roslib
Requires:       ros-jade-rospy
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-easy-markers
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-kalman-filter
BuildRequires:  ros-jade-people-msgs
BuildRequires:  ros-jade-roslib
BuildRequires:  ros-jade-rospy

%description
Track the output of the leg_detector to indicate the velocity of person.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon Jan 04 2016 David V. Lu!! <davidvlu@gmail.com> - 1.0.10-0
- Autogenerated by Bloom

